#!/bin/bash
# Tea Timer
# By default, gives you a timer for making tea.  By default, it's set to 
# five minutes

time=5

if [[ "$1" =~ ^[0-9]+$ ]]; then
	time=$1
fi

unit=$( bc <<< "scale=2; $time * 60 / 100" )

(
	echo "icon: /usr/share/pixmaps/faces/coffee.jpg"
	echo "visible: true"
	sleep $unit
	counter=0
	while [ "$counter" -le 99 ]; do
		mod=$(expr $counter % 50)
		if [[ "$mod" == "0" ]]; then
			echo "message:${counter}% done"
		fi
		#echo "tooltip: $counter%"
		sleep $unit
		counter=$(( $counter + 1 ))
	done
	echo "message: tea is done"
) | zenity --notification --text="tea timer" --listen
zenity --warning --text="Tea is done" --window-icon=/usr/share/pixmaps/faces/coffee.jpg
